# Generated by Django 5.0.2 on 2024-05-23 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
